"""
n8n Workflow Export — Phase C

Generates an IMPORTABLE n8n workflow JSON skeleton for a validated
automation opportunity. This is a suggestion the user reviews and
wires up themselves (credentials, exact API calls) — never an
automatic deployment (Master Instruction, section 22). The exported
workflow is always inactive ("active": false).

Design choices:
- Only node types CONFIRMED to exist in a stock n8n install are used
  for real integrations (Microsoft Excel, Microsoft Teams, Google
  Sheets). Every other application becomes a NoOp placeholder node
  with an explanatory sticky note, rather than guessing at a node
  type string that might not exist on the user's n8n version — a
  wrong guess would show as a broken/unrecognized node on import.
- Google Sheets special case: our workflow tokens don't carry a
  distinct "Google Sheets" application — a Sheets tab lives inside a
  Chrome step, tagged with a [sheet_tab:N] suffix (see
  mining/sequence_miner.py). This is where that earlier engineering
  effort visibly pays off: a step recorded as
  "chrome.exe:APP_SWITCH:sheet_tab_123..." becomes a real Google
  Sheets node here, not a generic browser placeholder.
"""

from __future__ import annotations

import re
import uuid
from typing import List, Tuple

_SHEET_TAB_MARKER = "sheet_tab_"


def _normalize_app_key(raw_app: str) -> str:
    """Normalizes raw telemetry app names (a mix of clean synthetic
    names like 'Chrome' and real psutil process names like
    'chrome.exe') to a canonical lookup key."""
    return re.sub(r"\.exe$", "", raw_app, flags=re.IGNORECASE).strip().lower()


# canonical_key -> (display_name, n8n node type, typeVersion, default parameters)
# Only apps we are CONFIDENT have this exact node type in a stock n8n
# install get a real integration node.
_KNOWN_NODES = {
    "excel": (
        "Microsoft Excel",
        "n8n-nodes-base.microsoftExcel",
        2.1,
        {"resource": "worksheet", "operation": "getContent"},
    ),
    "teams": (
        "Microsoft Teams",
        "n8n-nodes-base.microsoftTeams",
        2,
        {"resource": "chatMessage", "operation": "create"},
    ),
}

_DISPLAY_NAME_OVERRIDES = {
    "chrome": "Chrome (browser)",
    "windowsterminal": "Terminal",
    "explorer": "File Explorer",
    "chatgpt": "ChatGPT",
    "code": "VS Code",
}


def _display_name(app_key: str) -> str:
    if app_key in _DISPLAY_NAME_OVERRIDES:
        return _DISPLAY_NAME_OVERRIDES[app_key]
    return app_key.replace("_", " ").title()


def _collapse_steps_to_apps(steps: List[str]) -> List[Tuple[str, bool]]:
    """Collapses consecutive same-app tokens into one entry per app,
    in order of first appearance. Returns (app_key, is_sheet) pairs —
    is_sheet is True when a Chrome step carried a [sheet_tab:N]
    marker, meaning it's really a Google Sheets interaction."""
    collapsed: List[Tuple[str, bool]] = []
    last_key = None

    for step in steps:
        parts = step.split(":")
        raw_app = parts[0]
        is_sheet = any(p.startswith(_SHEET_TAB_MARKER) for p in parts[1:])
        app_key = "google_sheets" if is_sheet else _normalize_app_key(raw_app)

        if app_key != last_key:
            collapsed.append((app_key, is_sheet))
            last_key = app_key

    return collapsed


def _make_sticky_note(name: str, text: str, x: int, y: int, width: int = 380, height: int = 160) -> dict:
    return {
        "id": str(uuid.uuid4()),
        "name": name,
        "type": "n8n-nodes-base.stickyNote",
        "typeVersion": 1,
        "position": [x, y],
        "parameters": {"content": text, "height": height, "width": width},
    }


def build_n8n_workflow(opportunity) -> dict:
    """Builds a self-contained, importable n8n workflow JSON for the
    given Opportunity. Always exported inactive — activating it is a
    deliberate decision for the person to make in n8n, after
    reviewing and configuring credentials for each step."""

    apps = _collapse_steps_to_apps(opportunity.steps)

    nodes: List[dict] = []
    connections: dict = {}

    step_x_start = 260
    step_x_gap = 260
    row_y = 300

    trigger_name = "When clicking \u2018Test workflow\u2019"
    nodes.append({
        "id": str(uuid.uuid4()),
        "name": trigger_name,
        "type": "n8n-nodes-base.manualTrigger",
        "typeVersion": 1,
        "position": [0, row_y],
        "parameters": {},
    })

    overview_text = (
        f"## {opportunity.workflow_name}\n\n"
        f"{opportunity.description}\n\n"
        f"**Evidence:** {opportunity.frequency_per_week:.1f}/week \u00b7 "
        f"{opportunity.time_spent_hours_per_week:.1f}h/week \u00b7 "
        f"opportunity score {opportunity.opportunity_score:.0f}/100\n\n"
        f"Generated by Friction Miner as a starting point \u2014 review every "
        f"node's credentials and logic before activating. This workflow "
        f"is exported inactive on purpose."
    )
    nodes.append(_make_sticky_note("Overview", overview_text, x=0, y=row_y - 260, width=420, height=220))

    previous_name = trigger_name

    for i, (app_key, _is_sheet) in enumerate(apps):
        x = step_x_start + i * step_x_gap
        node_id = str(uuid.uuid4())

        if app_key == "google_sheets":
            name = f"Google Sheets ({i + 1})"
            node = {
                "id": node_id,
                "name": name,
                "type": "n8n-nodes-base.googleSheets",
                "typeVersion": 4,
                "position": [x, row_y],
                "parameters": {"operation": "append"},
            }
        elif app_key in _KNOWN_NODES:
            display, node_type, type_version, default_params = _KNOWN_NODES[app_key]
            name = f"{display} ({i + 1})"
            node = {
                "id": node_id,
                "name": name,
                "type": node_type,
                "typeVersion": type_version,
                "position": [x, row_y],
                "parameters": dict(default_params),
            }
        else:
            display = _display_name(app_key)
            name = f"{display} step ({i + 1})"
            node = {
                "id": node_id,
                "name": name,
                "type": "n8n-nodes-base.noOp",
                "typeVersion": 1,
                "position": [x, row_y],
                "parameters": {},
            }
            note_text = (
                f"**{display}** doesn't have a confirmed built-in n8n node for "
                f"this step. Replace this placeholder with an HTTP Request "
                f"node, a community node for {display}, or a browser-automation "
                f"step, depending on what {display} exposes."
            )
            nodes.append(_make_sticky_note(f"{display} note", note_text, x=x - 40, y=row_y + 160, width=300, height=140))

        nodes.append(node)

        connections[previous_name] = {
            "main": [[{"node": name, "type": "main", "index": 0}]]
        }
        previous_name = name

    return {
        "name": f"[Friction Miner] {opportunity.workflow_name}",
        "nodes": nodes,
        "connections": connections,
        "active": False,
        "settings": {"executionOrder": "v1"},
    }